sudo: required

branches:
  only: 
    - master

services:
  - docker

before_install:
  - TRAVIS_ENABLED=true

script: bash generate.sh

after_error: 
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:      
  - cd output/docs
  - sudo git init
  - sudo git config user.name "${GH_USER}"
  - sudo git config user.email "${GH_EMAIL}"
  - sudo git add .
  - sudo git commit -m "Deploy to GitHub Pages"
  - sudo git push --force --quiet "https://${GH_TOKEN}@github.com/fabric8-services/fabric8-devdoc" master:gh-pages > /dev/null 2>&1
