# jekyll configuration

title: "ALMighty-devdoc"

collections:
  blueprints:
    output: true

asciidoctor:
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

defaults:
  - scope:
      path: ""
      type: blueprints
    values:
      layout: blueprint
      
# end of configuration
